---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PabloRomeroGonzalez/ConfigData
        native:
          searchLocations: classpath:offline-repository/

server:
  port: 8001
# For simplicity, disable security when posting to bus/refresh:  
management:
  security:
    enabled: false