spring:
  cloud:
    config:
      server:
        git:
          //uri: https://github.com/PabloRomeroGonzalez/ConfigData
          uri: file:C:/Users/pablo.romero/Documents/PabloGit/ConfigData
          clone-on-start: true
server:
  port: 8001
  